# Homepage Config
isSinglePage: false

# Meta Config
description: "Nick Fisher's tech blog"

# Header Configuration
avatar: "img/nick-headshot.jpg"

# Favicon
favicon: "img/nficon.png"

# Disqus is a comment system. see https://disqus.com
disqusShortname: ""

emoji:
  enableEmoji: true

# Giscus is a comment system based on GitHub Discussions. see https://giscus.app
giscus:
  enable: false
  repo: ""
  repoId: ""
  category: "Announcements"
  categoryId: ""
  # mapping: "pathname"  # comment value is the default value
  # strict: 0
  # reactionsEnabled: 1
  # emitMetadata: 0
  # inputPosition: "top"
  # theme: "light"
  # lang: "zh-CN"
  # lazyLoading: true
